I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    pause
  File "renpy/common/000statements.rpy", line 462, in execute_pause
    renpy.pause()
  File "game/locations/natic.rpy", line 2, in execute
    screen natic():
  File "game/locations/natic.rpy", line 2, in execute
    screen natic():
  File "game/locations/natic.rpy", line 52, in execute
    add mc_images["mc_base"] at zoom_and_position_mc_right
  File "game/locations/natic.rpy", line 52, in keywords
    add mc_images["mc_base"] at zoom_and_position_mc_right
  File "game/locations/natic.rpy", line 52, in <module>
    add mc_images["mc_base"] at zoom_and_position_mc_right
NameError: name 'zoom_and_position_mc_right' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    pause
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 1980, in execute
    self.call("execute")
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/ast.py", line 1959, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 462, in execute_pause
    renpy.pause()
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/exports/statementexports.py", line 194, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay, pause_modal=modal)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "/Users/gergelykiss/Documents/renpy-8.3.4-sdk/renpy/display/screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/locations/natic.rpy", line 2, in execute
    screen natic():
  File "game/locations/natic.rpy", line 2, in execute
    screen natic():
  File "game/locations/natic.rpy", line 52, in execute
    add mc_images["mc_base"] at zoom_and_position_mc_right
  File "game/locations/natic.rpy", line 52, in keywords
    add mc_images["mc_base"] at zoom_and_position_mc_right
  File "game/locations/natic.rpy", line 52, in <module>
    add mc_images["mc_base"] at zoom_and_position_mc_right
NameError: name 'zoom_and_position_mc_right' is not defined

macOS-15.3.1-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
LB 1.0
Mon Mar  3 09:49:11 2025
